FROM python:3.12-slim-bookworm

WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get upgrade -y && \
    rm -rf /var/lib/apt/lists/*


COPY requirement.txt .

RUN pip install -r requirement.txt

COPY app.py .

RUN useradd Nikita
USER Nikita


EXPOSE 5000

CMD ["gunicorn", "--bind" , "0.0.0.0:5000","app:app"]
