FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY requirement.txt .

RUN pip install -r requirement.txt

COPY app.py .

RUN useradd Nikita
USER Nikita


EXPOSE 5000

CMD ["gunicorn", "--bind" , "0.0.0.0:5000","app:app"]
